### ISSUE TITLE
AssertionError: Output colors mismatch - could not find end of color marker!

### ISSUE THREAD

**Issue by C3R3** [mgeeky/decode-spam-headers#14]
I get this error when running the script for the first time. Latest Python3 3.11 and have all requirement.txt dependencies installed.

Script ran:
py .\decode-spam-headers.py EmailHeaders\headers.txt -f html -o headersreport.html
Traceback (most recent call last):
  File "C:\Python\decode-spam-headers-main\decode-spam-headers.py", line 6921, in <module>
    main(sys.argv)
  File "C:\Python\decode-spam-headers-main\decode-spam-headers.py", line 6904, in main
    output = colorizeOutput(printed, text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\decode-spam-headers-main\decode-spam-headers.py", line 6819, in colorizeOutput
    out = Logger.htmlColors(out)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\decode-spam-headers-main\decode-spam-headers.py", line 307, in htmlColors
    return Logger.replaceColors(s, get_col)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\decode-spam-headers-main\decode-spam-headers.py", line 267, in replaceColors
    assert pos2 != -1, "Output colors mismatch - could not find end of color marker!"
           ^^^^^^^^^^
AssertionError: Output colors mismatch - could not find end of color marker!

**Comment by C3R3** [comment]
Just an FYI, the script will work if I disable colors. Awesome tool by the way, thank you!

**Comment by mgeeky** [comment]
Hey man!

Thank you for reporting this one, looks really nasty. Is it possible you send me (paste it here maybe or send to my email) an anonymized input you used that made the script crash? :)

Unsure how to reproduce it without having some input data.

Best regards,
Mariusz.

**Comment by derainbow** [comment]
I think the problem is either your python version or you did not install all dependencies.

**Comment by mediatech15** [comment]
@mgeeky Do you still need sample email headers for testing this. I have started to run into this issue also.
